---
elasticsearch_certs_path: /etc/elasticsearch/certs
logstash_certs_path: /etc/logstash/certs
kibana_certs_path: /etc/kibana/certs
beats_certs_path: /etc/filebeat/certs

file_owner: root
file_group: root
file_mode_cert: '0644'
file_mode_key: '0640'

# Пользователи и пароли (замените на свои)
elasticsearch_user: elastic
elasticsearch_password: "changeme_elastic_password"

logstash_user: logstash_writer
logstash_password: "changeme_logstash_password"
logstash_elasticsearch_hosts:
  - "https://192.168.88.12:9200"

kibana_user: kibana_system
kibana_password: "changeme_kibana_password"
kibana_elasticsearch_hosts:
  - "https://192.168.88.12:9200"

beats_http_ca_crt: http_ca.crt
beats_elasticsearch_hosts:
  - "https://192.168.88.12:9200"
beats_logstash_hosts:
  - "192.168.88.12:5044"
beats_user: filebeat_writer
beats_password: "changeme_filebeat_password"