---
j2:
  templates:
    elasticsearch:
      path:
        data: "/var/lib/elasticsearch"
        logs: "/var/log/elasticsearch"
      xpack:
        security_enabled: true
        enrollment_enabled: true
        http:
          ssl:
            enabled: true
            keystore_path: "certs/http.p12"
        transport:
          ssl:
            enabled: true
            keystore_path: "certs/transport.p12"
            truststore_path: "certs/transport.p12"
          verification:
            mode: "certificate"
      cluster:
        initial:
          master:
            nodes:
              - "ELK"
      http:
        host: "127.0.0.1"
    logstash:
      beats:
        port: 5044
        ssl:
          enabled: true
          certificate: "/test/cert.crt"
          key: "/test/cert.key"
      elasticsearch:
        http:
          port: 9200
          host: "127.0.0.1"
        user: "elastic"
        password: "asuw2vjIXgpbfAsay78?En7aXg#GwVf9b67xtdyEVlZbmFlP"
      ssl:
        enabled: true
        cacert:
          path: "/etc/logstash/certs/http_ca.crt"
move:
  crt:
    src: "files/http_ca.crt"
    dst: "/etc/logstash/certs/http_ca.crt"