---
- name: Installing Base Packages
  hosts: all
  become: yes
  roles:
    - common

- name: Configuring WEB SRV
  hosts: WEB_SRV
  become: yes
  roles:
    - WEB_SRV_INSTALL

# - name: Configuring PAM