---
- name: INSTALLING BASE PACKAGES
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: RESTART NGINX

- name: ADD Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: absent

- name: Add Elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: absent
    filename: elastic-8.x

- name: Update apt cache
  apt:
    update_cache: yes

- name: INSTALLING BASE PACKAGES
  apt:
    name: "{{ package.name }}"
    state: present
    update_cache: yes


