---
- name: INSTALLING BASE PACKAGES
  apt:
    name: nginx
    state: present
    update_cache: yes
  notify: RESTART NGINX

#- name: Download and add GPG key from mirror.example.ru
#  ansible.builtin.get_url:
#    url: "https://mirror.example.ru/public.key"
#    dest: "/usr/share/keyrings/mirror-example-ru.gpg"
#    mode: '0644'


- name: Add Elastic repository from Yandex mirror
  apt_repository:
    repo: "deb https://mirror.yandex.ru/mirrors/elastic/8 stable main"
    filename: elastic-8.x
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: INSTALLING BASE PACKAGES
  apt:
    name: "{{ package.name }}"
    state: present
    update_cache: yes


