---
- name: Создать пользователей ELK (если ещё не созданы)
  user:
    name: "{{ item }}"
    system: yes
    shell: /usr/sbin/nologin
  loop:
    - elasticsearch
    - logstash
    - kibana

- name: Создать директории для сертификатов
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0755'
  loop:
    - { path: "{{ elasticsearch_certs_path }}", owner: "elasticsearch", group: "elasticsearch" }
    - { path: "{{ logstash_certs_path }}", owner: "logstash", group: "logstash" }
    - { path: "{{ kibana_certs_path }}", owner: "kibana", group: "kibana" }
    - { path: "{{ beats_certs_path }}", owner: "root", group: "root" }

- name: Копировать сертификаты в Elasticsearch
  copy:
    src: "certs/{{ item.src }}"
    dest: "{{ elasticsearch_certs_path }}/{{ item.dest }}"
    owner: elasticsearch
    group: elasticsearch
    mode: "{{ file_mode_cert }}"
  loop:
    - { src: "http_ca.crt", dest: "http_ca.crt" }
    - { src: "http.p12", dest: "http.p12" }
    - { src: "transport.p12", dest: "transport.p12" }

- name: Настроить elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'
  notify: restart elasticsearch

- name: Копировать CA сертификат для Logstash
  copy:
    src: "certs/http_ca.crt"
    dest: "{{ logstash_certs_path }}/http_ca.crt"
    owner: logstash
    group: logstash
    mode: "{{ file_mode_cert }}"

- name: Настроить конфигурацию Logstash
  template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
    owner: logstash
    group: logstash
    mode: '0644'
  notify: restart logstash

- name: Копировать CA сертификат для Kibana
  copy:
    src: "certs/http_ca.crt"
    dest: "{{ kibana_certs_path }}/http_ca.crt"
    owner: kibana
    group: kibana
    mode: "{{ file_mode_cert }}"

- name: Настроить kibana.yml
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    mode: '0644'
  notify: restart kibana

- name: Установить Filebeat на WEB_SRV
  apt:
    name: filebeat
    state: present
    update_cache: yes
  when: "'WEB_SRV' in group_names"

- name: Создать директорию для сертификатов Filebeat
  file:
    path: "{{ beats_certs_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: "'WEB_SRV' in group_names"

- name: Копировать CA сертификат для Filebeat
  copy:
    src: "certs/http_ca.crt"
    dest: "{{ beats_certs_path }}/http_ca.crt"
    owner: root
    group: root
    mode: "{{ file_mode_cert }}"
  when: "'WEB_SRV' in group_names"

- name: Настроить filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart filebeat
  when: "'WEB_SRV' in group_names"
